name: online_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  go_router: ^14.6.3
  bloc:
  flutter_bloc: ^8.1.6
  dio: ^5.8.0+1
  shared_preferences: ^2.5.1
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  bot_toast: ^4.1.3
  flutter_dotenv: ^5.2.1
  pretty_dio_logger: ^1.4.0
  get_it: ^8.0.3
  video_player: ^2.9.5
  chewie: ^1.11.3
  smooth_page_indicator: ^1.2.1
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  internet_connection_checker: ^3.0.1
  shimmer: ^3.0.0
  provider: ^6.1.5
  credit_card_type_detector: ^3.0.0
#  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  share_plus: ^11.0.0
  phone_numbers_parser: ^9.0.3

  mask_text_input_formatter: ^2.9.0
  liqpay: ^0.0.2
  uuid: ^4.5.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  url_launcher: ^6.3.1
  flutter_local_notifications: ^19.2.0
  widgetbook: ^3.14.2
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2
  timezone: ^0.10.1
  android_intent_plus: ^5.3.0
  device_info_plus: ^11.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  go_router_builder: ^2.8.2

  flutter_gen_runner: ^5.10.0
 

dependency_overrides:
  analyzer: ^6.2.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - lib/api_keys.env
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package